---
plugin: google.cloud.gcp_compute
zones:
  - us-east1-b
projects: 
  - magniops-dev
filters:
  - status = RUNNING
auth_kind: application
groups:
  proxy: "'magnigate' in labels.service_name"
hostnames:
  - public_ip
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP

