---
- name: Package Provisioning
  hosts: proxy
  become: true
  tasks:
    - name: Ping Host
      ansible.builtin.ping:
    - name: Runs 'apt-get update'
      ansible.builtin.apt:
        update_cache: yes
    - name: Pull project
      ansible.builtin.git:
        dest: /opt/www
        repo: 'https://github.com/magnizide/magnigate.git'
        single_branch: true
        version: "{{ REPO_REF }}"
    - name: Make All Target
      ansible.builtin.command:
        argv:
          - "make"
          - "-S"
          - "all"
        chdir: /opt/www
    - name: Gcloud pull certs
      ansible.builtin.command:
        argv:
          - gcloud
          - storage
          - cp
          - "gs://{{ CERTS_BUCKET }}/{{ PROJECT_ENV }}/{{ PROJECT_ENV }}-acme.json"
          - /opt/www/config/letsencrypt/acme.json
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/www/config/letsencrypt/acme.json
        owner: root
        group: root
        mode: '0600'
    - name: Pull images
      community.docker.docker_compose_v2_pull:
        project_src: /opt/www
    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /opt/www
      register: output
    - name: Show Compose results
      ansible.builtin.debug:
        var: output
