# GCP deployment
name: Deploy
on:
  push:
    branches:
      - "main"
      - "develop"

env:
  TF_WORKSPACE: ${{ vars.PROJECT_ENV }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_record_name: ${{ secrets.RECORD_NAME }}
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  TF_VAR_certs_bucket_name: ${{ secrets.CERTS_BUCKET_NAME }}
  TF_VAR_service_name: ${{ vars.SERVICE_NAME }}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    outputs:
      ssh_key: ${{ steps.private_key.outputs.ssh_key_string }}
    steps:
      - name: "Context"
        uses: actions/checkout@v4

      - name: "Environment validation"
        run: |
          echo "Deploying to ${{ vars.PROJECT_ENV }}..."
          echo "Working directory"
          pwd

      - name: Google auth
        id: 'applierAuth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_FILE }}'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.0'

      - name: Terraform format
        working-directory: terraform
        id: fmt
        run: terraform  fmt -recursive -check

      - name: Terraform init
        working-directory: terraform
        id: init
        run: terraform  init -no-color -input=false -backend-config="prefix=magnigate_states" --backend-config="bucket=${{ secrets.GCP_BUCKET_TF_STATE }}"

      - name: Terraform validate
        working-directory: terraform
        id: validate
        run: terraform  validate -no-color

      - name: Terraform plan
        working-directory: terraform
        id: plan
        run: terraform  plan -input=false -var-file=tfvars/${{ vars.PROJECT_ENV }}.tfvars

      - name: Terraform apply
        id: apply
        working-directory: terraform
        run: terraform  apply -input=false --auto-approve -var-file=tfvars/${{ vars.PROJECT_ENV }}.tfvars

      - name: Collect private key
        id: private_key
        working-directory: terraform
        run: |
          PRIVATE_KEY=$(terraform output -raw private_key | base64 -w 0)
          echo "::add-mask::$PRIVATE_KEY"
          echo "ssh_key_string=$PRIVATE_KEY" >> "$GITHUB_OUTPUT"

  configure_management:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    needs: deploy
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v4

      - name: Decode SSH
        id: decode
        env:
          SSH_KEY: ${{ needs.deploy.outputs.ssh_key }}
        run: |
          echo "SSH_ENV=$(echo $SSH_KEY | base64 --decode)" >> private_key
          chmod 0600 private_key

      - name: Google auth
        id: 'applierAuth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_FILE }}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create Virtual Environment
        run: python3 -m venv ansible_venv

      - name: Activate Virtual Environment
        run: source ansible_venv/bin/activate

      - name: Install Ansible and Dependencies
        run: |
          pip install ansible requests google-auth

      - name: Run Ansible Playbook
        run: |
          source ansible_venv/bin/activate
          ansible-playbook -i inventory/proxy.gcp.yaml playbooks/proxy.yaml -u ${{ secrets.REMOTE_USER }} --extra-vars "PROJECT_ENV=${{ vars.PROJECT_ENV }}" --extra-vars "CERTS_BUCKET=${{ secrets.CERTS_BUCKET_NAME }}" --private_key private_key
        env:
          ANSIBLE_CONFIG: ansible.cfg

