# GCP deployment
name: Deploy
on:
  push:
    branches:
      - "main"
      - "develop"

defaults:
  run:
    working-directory: terraform

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - name: "Context"
        uses: actions/checkout@v4

      - name: "Environment validation"
        run: |
          echo "Deploying to ${{ environment }}..."
          echo "Working directory"
          pwd

      - name: Google auth
        id: 'applierAuth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_FILE }}'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.0'

      - name: Terraform format
        id: fmt
        run: terraform  fmt -recursive -check

      - name: Terraform init
        id: init
        run: terraform  init -no-color -input=false -backend-config="prefix=magnigate_states" --backend-config="bucket=${{ secrets.GCP_BUCKET_TF_STATE }}"

      - name: Terraform validate
        id: validate
        run: terraform  validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform  plan -input=false -var "certs_bucket_name=${{ secrets.CERTS_BUCKET_NAME }}" -var-file=tfvars/${{ environment }}.tfvars

      - name: Terraform apply
        id: apply
        run: terraform  apply -input=false --auto-approve -var 'certs_bucket_name=${{ secrets.CERTS_BUCKET_NAME }} -var-file=tfvars/${{ environment }}.tfvars

